version: 0.2.{build}
image: Visual Studio 2017
branches:
  only:
  - master
configuration: Release
build_script:
- cmd: >-
    dotnet restore

    dotnet build -c Release

    dotnet pack ValidDotNet -c Release
test_script:
- cmd: dotnet test ValidDotNet.Tests.Unit\ValidDotNet.Tests.Unit.csproj
artifacts:
- path: ValidDotNet\bin\Release\*.nupkg
  name: nuget
deploy:
- provider: NuGet
  server: https://www.nuget.org/api/v2/package
  api_key:
    secure: 5+SUZKFkrKpiGjy/Kv2igz+SC8vio1U5xVWRsQRVKqXgehgmTe/5SXBXlcFZsykJ
  skip_symbols: false
  artifact: nuget